config/routes.rb
Rails.application.routes.draw do

  resources :sitemap, :only => :index
  get 'sitemap.xml', :controller => "sitemap", :action => "xml"

  resources :categories
  devise_for :users
  root 'promocodes#index'
  resources :promocodes

  get '/promocodes/hashtag/:name', to: 'promocodes#hashtags'

  get 'bridge/marketing'
  get 'bridge/posting'
  get 'bridge/search'
  get 'bridge/about_us'
  get 'bridge/withpromocode'
  get 'bridge/withcoupon'
  
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/promocode.rb
class Promocode < ApplicationRecord
  is_impressionable
  
  extend FriendlyId
  friendly_id :code_title, use: :slugged

  belongs_to :user
  validates :code_wacode_price, presence: true

  has_and_belongs_to_many :tags

  after_create do
    promocode = Promocode.find_by(id: self.id)
    hashtags = self.code_hashtag.scan(/[#＃][a-z|A-Z|가-힣|0-9|\w]+/)
    hashtags.uniq.map do |hashtag|
        tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
        promocode.tags << tag
    end
  end
  
  before_update do
    promocode = Promocode.find_by(id: self.id)
    promocode.tags.clear
    hashtags = self.code_hashtag.scan(/[#＃][a-z|A-Z|가-힣|0-9|\w]+/)
    hashtags.uniq.map do |hashtag|
        tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
        promocode.tags << tag
    end
  end

  def self.search_by(search_term)
    where("LOWER(code_title) LIKE :search_term", search_term: "%#{search_term.downcase}%")
   end 

end

app/controllers/promocodes_controller.rb
class PromocodesController < ApplicationController
  before_action :set_promocode, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index, :hashtags]

  # GET /promocodes
  # GET /promocodes.json
  def index
    @pagy, @promocodes = pagy(Promocode.all.order("created_at DESC"), items: 80)
    set_meta_tags title: 'The best Deals, Coupons, Promocodes on Amazon',
                  site: 'hotdealful',
                  revierse: true,
                  description: 'Find the best deals, coupons, promo codes on Amazon. Do not pay full price!!, save your money with us.',
                  keywords: 'amazondeals, hotdeals, promotion code, coupons ',
                  twitter: {
                    card: "summary",
                    site: "@hotdealful",
                    title: 'The best Deals, Coupons, Promocodes on Amazon',
                    description: 'Find the best deals, coupons, promo codes on Amazon. Do not pay full price!!, save your money with us.',
                    # image: @hotdeal.h_image
                  },
                  og: {
                    title: 'The best Deals, Coupons, Promocodes on Amazon',
                    description: 'Find the best deals, coupons, promo codes on Amazon. Do not pay full price!!, save your money with us.',
                    type: 'website',
                    url: 'www.hotdealful.com',
                    # image: @hotdeal.h_image
                  }
    @categories = Category.all
    if params[:search]
      @search_term = params[:search]
      @promocodes = @promocodes.search_by(@search_term)
    end
  end



  # GET /promocodes/1
  # GET /promocodes/1.json
  def show
    impressionist(@promocode)
    set_meta_tags title: @promocode.code_title,
                  site: 'hotdealful',
                  revierse: true,
                  description: @promocode.code_title,
                  keywords: 'amazondeals, hotdeals, promotion code, coupons ',
                  twitter: {
                    card: "summary",
                    site: "@hotdealful",
                    title: @promocode.code_title,
                    description: @promocode.code_title,
                    image: @promocode.code_image
                  },
                  og: {
                    title: @promocode.code_title,
                    description: @promocode.code_title,
                    type: 'website',
                    url: promocode_url(@promocode),
                    image: @promocode.code_image
                  }
  end

  def hashtags
    tag = Tag.find_by(name: params[:name])
    @pagy, @promocodes = pagy(tag.promocodes.order("created_at DESC"), items: 80)
    @categories = Category.all
  end

  # GET /promocodes/new
  def new
    @promocode = Promocode.new
  end

  # GET /promocodes/1/edit
  def edit
  end

  # POST /promocodes
  # POST /promocodes.json
  def create
    @promocode = Promocode.new(promocode_params)
    @promocode.user = current_user
    respond_to do |format|
      if @promocode.save
        format.html { redirect_to @promocode, notice: 'Promocode was successfully created.' }
        format.json { render :show, status: :created, location: @promocode }
      else
        format.html { render :new }
        format.json { render json: @promocode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promocodes/1
  # PATCH/PUT /promocodes/1.json
  def update
    respond_to do |format|
      if @promocode.update(promocode_params)
        format.html { redirect_to @promocode, notice: 'Promocode was successfully updated.' }
        format.json { render :show, status: :ok, location: @promocode }
      else
        format.html { render :edit }
        format.json { render json: @promocode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promocodes/1
  # DELETE /promocodes/1.json
  def destroy
    @promocode.destroy
    respond_to do |format|
      format.html { redirect_to promocodes_url, notice: 'Promocode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promocode
      @promocode = Promocode.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def promocode_params
      params.require(:promocode).permit(:code_title, :code_hashtag, :code_link, :code_image, :code_source, :code_rating, 
                                        :code_review_count, :code_icode_price, :code_wacode_price, :code_pct, :code_description, 
                                        :code_spare_01, :code_spare_41, :code_spare_42)
    end
end

app/helpers/promocodes_helper.rb
module PromocodesHelper
  def render_with_hashtags(code_hashtag)
    code_hashtag.gsub(/[#＃][a-z|A-Z|가-힣|0-9|\w]+/){|word| link_to word, "/promocodes/hashtag/#{word.delete('#')}"}.html_safe
  end 
end

app/views/promocodes/_categories.html.erb
<div class="category-pc clearfix" data-turbolinks="false">
  <ul>
    <li><a href="/">Everything</a></li>
    <li><a href="/promocodes/hashtag/electronics">Electronics,</a></li>
    <li><a href="/promocodes/hashtag/home">Home,</a></li>
    <li><a href="/promocodes/hashtag/kitchen">Kitchen,</a></li>
    <li><a href="/promocodes/hashtag/fashion">Fashion,</a></li>
    <!-- <li><a href="/promocodes/hashtag/beauty">Beauty,</a></li> -->
    <!-- <li><a href="/promocodes/hashtag/health">Health,</a></li> -->
    <li><a href="/promocodes/hashtag/outdoor">Outdoor,</a></li>
    <li><a href="/promocodes/hashtag/pet_supplies">Pet Supplies</a></li>
    
  </ul>
</div>



<div class="category-mobile clearfix" data-turbolinks="false">
  <nav>
    <ul class="left">
      <li><a href="/">Everything</a></li>
      <li><a href="/promocodes/hashtag/electronics">Electronics,</a></li>
      <li><a href="/promocodes/hashtag/home">Home,</a></li>
      <li><a href="/promocodes/hashtag/kitchen">Kitchen,</a></li>
      <li><a href="/promocodes/hashtag/fashion">Fashion,</a></li>
      <!-- <li><a href="/promocodes/hashtag/beauty">Beauty,</a></li> -->
      <!-- <li><a href="/promocodes/hashtag/health">Health,</a></li> -->
      <li><a href="/promocodes/hashtag/outdoor">Outdoor,</a></li>
      <li><a href="/promocodes/hashtag/pet_supplies">Pet Supplies</a></li>
    </ul>
    <ul class="right">
      <!-- <li><a href="/bridge/more_sale">+ More</a></li> -->
    </ul>
  </nav>
</div>


<script type="text/javascript">
  $(window).scroll(function (e) {
    let nav = $('nav');
    let scrolled = $(window).scrollTop();
    if (scrolled > 70) {
      nav.addClass('fixed');
    } else {
      nav.removeClass('fixed');
    }
  });
</script>

app/views/promocodes/_find_coupon.html.erb
<div class="find-coupon clearfix">

  <div class="couponbox-left">
    <p>FIND AMAZON COUPONS</p>
    <span>√ You can search for items including coupons.</span>
    <span>√ Save your money with coupons.</span>
    <span>√ If you want to search in more detail, click <a href="/bridge/search">Search Detail</a></span>
  </div>  


  <div class="couponbox-right">
    <div class="find-keyword">
      <div class="keyword_box clearfix">
        <input type="text" class="keyword" placeholder="Search coupon here" value="">
      </div>
    </div>
    
    <div class="index-coupon">
      <div class="option_box">  
        <div class="on_off clearfix">
          <input id="coupon" name="coupon-type" type="radio" value="2231352011" checked>
          <label for="coupon">ON</label>
        </div>
      </div>
    </div>

    <div class="find-btn">
      <button class="search findcoupon btn-comm">Find Coupons</button>
      <!-- <a href="/bridge/search" class="detailsearch btn-comm" href="/bridge/search">Search Detail</a> -->
    </div>
  </div>
  
</div>


<script type="text/javascript">
  //Search on Amazon[quick search]//
  function isMobile(){
  var UserAgent = navigator.userAgent;

  if (UserAgent.match(/iPhone|iPod|Android|Windows CE|BlackBerry|Symbian|Windows Phone|webOS|Opera Mini|Opera Mobi|POLARIS|IEMobile|lgtelecom|nokia|SonyEricsson/i) != null || UserAgent.match(/LG|SAMSUNG|Samsung/) != null)
    {
      return true;
    }else{
      return false;
    }
  }

  if(isMobile()){
      //For Mobile
      $(document).ready(function(){
      var rootURL = "https://www.amazon.com/s?i=aps";

      $("select[name='time']").change(function(){
        if ( $(this).val() === "custom" ){
          $(".custom-time").removeClass("disable");
        } else {
          $(".custom-time").addClass("disable");
        }
      });
      
      $(".search").on("click", function(){
        var couponType = $("input:radio[name='coupon-type']:checked").val();
        var keyWord = $(".keyword").val();
        
        var key  = (keyWord === "") ? "" : "&field-keywords=" + keyWord;
        var coupon = (couponType === "") ? "" : "&srs=" + couponType;
        
        var query = rootURL + key + coupon + "&tag=oigbt-20";
        window.open(query, '_blank');
        
      });
    });


  }else{

      //For PC
      $(document).ready(function(){
      var rootURL = "https://www.amazon.com/s?k=";

      $("select[name='time']").change(function(){
        if ( $(this).val() === "custom" ){
          $(".custom-time").removeClass("disable");
        } else {
          $(".custom-time").addClass("disable");
        }
      });
      
      $(".search").on("click", function(){
        var couponType = $("input:radio[name='coupon-type']:checked").val();
        var keyWord = $(".keyword").val();
        
        var key  = (keyWord === "") ? "" : keyWord;
        
        var coupon = (couponType === "") ? "" : "&srs=" + couponType;        
        var query = rootURL + key + coupon + "&tag=oigbt-20";

        window.open(query, '_blank');
        
      });
    });

  }
  //End//

</script>

app/views/promocodes/_form.html.erb
<div class="hotdeal_form">
  <%= simple_form_for(@promocode) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="basic_info">
      <%= f.input :code_image, label: "Image URL" %>
      <%= f.input :code_link, label: "Product URL" %>
      <%= f.input :code_title, label: "Product Title" %>
      <%= f.input :code_hashtag, label: "Hashtag" %>
      <%= f.input :code_spare_01, label: "Promotion Code" %>
    </div>
    <div class="pricing clearfix">
      <%= f.input :code_wacode_price, label: "List Price" %>
      <%= f.input :code_icode_price, label: "Current Price(for hotdeal)" %>
      <%= f.input :code_pct, label: "Percentage(for code)" %>
      <%= f.input :code_spare_41, label: "Coupon by $$" %>
      <%= f.input :code_spare_42, label: "Coupons by pct" %>
    </div>
    
    <!-- <div class="pricing">
      <%= f.input :code_rating, label: "Rating" %>
      <%= f.input :code_review_count, label: "Review Count" %>
    </div> -->
    

    <div class="form-actions" data-turbolinks="false">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/promocodes/_header.html.erb
<nav>
  <input type="checkbox" id="nav" class="hidden"/>
  <label for="nav" class="nav-open"><i></i><i></i><i></i></label>
  <div class="nav-container">
    <ul>
      <li><a href="#">Work</a></li>
      <li><a href="#">About</a></li>
      <li><a href="#">Careers</a></li>
      <li><a href="#">Contact</a></li>
    </ul>
  </div>
</nav>

app/views/promocodes/_sns.html.erb
<a class="facebook" id="shareFB" href="https://www.facebook.com/sharer/sharer.php?u=<%= url_for([@promocode, { 
 only_path: false }]) %>&t=<%= @promocode.code_title %>"
 onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"  target="_blank" title="Share on Facebook"><!-- <li><i class="fa fa-facebook"></i> --><span>Facebook</span></a> 
<script type="text/javascript">document.getElementById("shareFB").setAttribute("href", "https://www.facebook.com/sharer/sharer.php?u=" + document.URL);</script>

app/views/promocodes/edit.html.erb
<% if current_user && current_user.admin %>
  <div class="wrap" data-turbolinks="false">
    <h1>Editing Promocode</h1>
    <%= render 'form', promocode: @promocode %>
    <%= link_to 'Show', @promocode %> |
    <%= link_to 'Back', promocodes_path %>
  </div>
<% end %>

app/views/promocodes/hashtags.html.erb
<div class="top-box"></div>
<div class="index-wrap">

  <div class="wrap">


    <div class="visual">
      <p>Don't pay full price! Save your money!</p>
      <h1><a href="/" data-turbolinks="false">HOTDEAL-FUL</a>
        <% if current_user && current_user.admin %>
          <%= link_to 'New Promocode', new_promocode_path %>
        <% end %>
      </h1>
      <div class="search-index">
        <%= form_for "",url: promocodes_path, role: "search", method: :get do %>
          <%= text_field_tag :search, @search_term, placeholder: "Search..." %>
        <% end %> 
      </div>   
      <%= render 'categories/list' %>

       <div class="where-hashtag">
        <% if params[:name].present? %>
          <p><span class="hashtag-through">#<%= params[:name] %></span></p>
        <% end %>
      </div>
    </div>


    <div class="product-border clearfix">
      <% @promocodes.each do |promocode| %>
        <div class="card">
          <div class="image-box">
            <a href="/promocodes/<%= promocode.id %>"><img src="<%= promocode.code_image %>" alt="<%= promocode.code_title %>" title="<%= promocode.code_title %>"></a>
          </div>
          <div class="inner">
            <p class="line-break-01"><%= link_to promocode.code_title, promocode %></p>

            <% if promocode.code_spare_01.present? %>
              <% promocode_price = 0 %>
              <% promocode_price =  promocode.code_wacode_price - (promocode.code_pct / 100) * promocode.code_wacode_price %>
              <span class="list_price"><%= number_to_currency(promocode.code_wacode_price) %></span>
              <span class="current_price"><%= number_to_currency(promocode_price) %></span>
            <% else %>
              <span class="list_price"><%= number_to_currency(promocode.code_wacode_price) %></span>
              <span class="current_price"><%= number_to_currency(promocode.code_icode_price) %></span>
            <% end %>
            
          </div>
          <% if promocode.code_spare_01.present? %>
            <div class="pct"><p><%= number_to_percentage(promocode.code_pct, precision: 0) %></p></div>
          <% else %>
            <% hotdeal_pct = 0 %>
            <% hotdeal_pct =  (promocode.code_wacode_price - promocode.code_icode_price) / promocode.code_wacode_price * 100 %>
            <div class="pct"><p><%= number_to_percentage(hotdeal_pct, precision: 0) %></p></div>
          <% end %>
        </div>
      <% end %>

    </div>
    <%= raw pagy_nav(@pagy) %>


  </div><!--./wrap-->
</div><!--./index-wrap->

app/views/promocodes/index.html.erb
<div class="top-box"></div>
<div class="index-wrap">

  <div class="wrap">

    <div class="visual">
      <p>Don't pay full price! Save your money!</p>
      <h1><a href="/" data-turbolinks="false">HOTDEAL-FUL</a>
        <% if current_user && current_user.admin %>
          <%= link_to 'New Promocode', new_promocode_path %>
        <% end %>
      </h1>
      <div class="search-index">
        <%= form_for "",url: promocodes_path, role: "search", method: :get do %>
          <%= text_field_tag :search, @search_term, placeholder: "Search today's hot deal..." %>
        <% end %> 
      </div>   
      <%= render 'categories/list' %>
    </div><!--./visual-->

    <div class="find-coupon-box">
      <%= render 'promocodes/find_coupon' %>
    </div>

    <% if current_user && current_user.admin %>
      <div class="index-amdin clearfix" data-turbolinks="false">
        <p>I am Admin!!!!!</p>
        
        <%= link_to 'Categories', categories_path %>
        <a href="/bridge/marketing">Marketing</a>
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
      </div>
    <% end %>

    <div class="pick-hash">
      <a class=".hashtag-through" href="/promocodes/hashtag/50_percent_or_more">#50% off or more</a>
      <a href="/promocodes/hashtag/under_10_dollars">#Under $10</a>
      <a href="/bridge/withpromocode">#Promotion Codes</a>
      <!-- <a href="/bridge/withcoupon">#With Coupons</a> -->
    </div>

    <div class="product-border clearfix">
      <% @promocodes.each do |promocode| %>
        <div class="card">
          <div class="image-box">
            <!-- <a href="/promocodes/<%= promocode.id %>" data-turbolinks="false"><img src="<%= promocode.code_image %>" alt="<%= promocode.code_title %>" title="<%= promocode.code_title %>"></a> -->
            <%= link_to image_tag(promocode.code_image), promocode %>
          </div>
          <div class="inner">
            <p class="line-break-01" data-turbolinks="false"><%= link_to promocode.code_title, promocode%></p>

            <% if promocode.code_spare_01.present? %>
              <% promocode_price = 0 %>
              <% promocode_price =  promocode.code_wacode_price - (promocode.code_pct / 100) * promocode.code_wacode_price %>
              <span class="list_price"><%= number_to_currency(promocode.code_wacode_price) %></span>
              <span class="current_price"><%= number_to_currency(promocode_price) %></span>
            <% else %>
              <span class="list_price"><%= number_to_currency(promocode.code_wacode_price) %></span>
              <span class="current_price"><%= number_to_currency(promocode.code_icode_price) %></span>
            <% end %>
            
          </div>
          <% if promocode.code_spare_01.present? %>
            <div class="pct"><p><%= number_to_percentage(promocode.code_pct, precision: 0) %> off</p></div>
          <% else %>
            <% hotdeal_pct = 0 %>
            <% hotdeal_pct =  (promocode.code_wacode_price - promocode.code_icode_price) / promocode.code_wacode_price * 100 %>
            <div class="pct"><p><%= number_to_percentage(hotdeal_pct, precision: 0) %> off</p></div>
          <% end %>
          <% if current_user && current_user.admin %>
            <span class="view">view:<%= promocode.impressionist_count %></span>
            <span class="delete"><%= link_to 'Destroy', promocode, method: :delete, data: { confirm: 'Are you sure?' } %></span>
          <% end %>
        </div>
      <% end %>

    </div>
    <%= raw pagy_nav(@pagy) %>


  </div><!--./wrap-->
  <%= render 'shared/footer' %>
</div><!--./index-wrap->

app/views/promocodes/new.html.erb
<% if current_user && current_user.admin %>
  <div class="wrap">
    <h1>New Promocode</h1>
    <%= render 'form', promocode: @promocode %>
    <%= link_to 'Back', promocodes_path %>
  </div>
<% end %>